subject = {
    "Human Characters": ["woman", "man", "girl", "boy", "baby"],
    "Animals": [
        "cat",
        "dog",
        "fish",
        "bird",
        "snake",
        "elephant",
        "tiger",
        "lion",
        "bear",
        "panda",
        "monkey",
        "fox",
        "wolf",
        "deer",
        "rabbit",
        "horse",
        "cow",
        "sheep",
        "goat",
        "pig",
        "chicken",
        "duck",
        "goose",
        "dragon",
        "dinosaur",
        "unicorn",
    ],
    "Fantasy": [
        "pumpkin head",
        "fish head",
        "angel",
        "demon",
        "vampire",
        "werewolf",
        "zombie",
        "ghost",
        "witch",
        "wizard",
        "fairy",
        "mermaid",
        "elf",
        "orc",
        "dwarf",
        "fairy",
        "mermaid",
        "monster",
        "goblin",
    ],
    "Objects and others": ["robot", "alien"],
    "Profession": ["knight", "ninja", "pirate", "astronaut", "clown"],
}

subject_list = [item for sublist in subject.values() for item in sublist]

age = [
    "newborn",
    "toddler",
    "around 5 years old",
    "teenager",
    "young adult",
    "around 30 years old",
    "middle-aged",
    "elderly",
]

style = [
    "cartoon",
    "pixel art",
    "anime",
    "pop art",
    "impressionistic",
    "Stylized Realism",
    "manga",
    "Chibi",
    "low poly",
    "disney",
    "High Fantasy",
    "sci-fi",
    "cyberpunk",
    "steampunk",
    "gothic",
    "Surrealism",
]

headwear = [
    "hat",
    "cap",
    "helmet",
    "crown",
    "tiara",
    "headband",
    "headphones",
    "headset",
    "glasses",
    "sunglasses",
    "mask",
    "scarf",
    "hood",
    "astronaut helmet",
    "firefighter helmet",
    "knight's helmet",
    "goggles",
]

eye_color = [
    "black",
    "brown",
    "blue",
    "green",
    "hazel",
    "gray",
    "red",
    "purple",
    "yellow",
    "orange",
    "pink",
    "teal",
    "cyan",
    "white",
]

hair_color = [
    "black",
    "brown",
    "blonde",
    "red",
    "gray",
    "white",
    "blue",
    "green",
    "purple",
    "pink",
    "orange",
    "yellow",
    "teal",
    "cyan",
]

hair_style = [
    "short",
    "medium",
    "long",
    "curly",
    "straight",
    "wavy",
    "spiky",
    "bald",
    "mohawk",
    "afro",
    "dreadlocks",
    "ponytail",
    "bun",
    "braids",
    "pigtails",
    "bangs",
    "fringe",
    "quiff",
    "slicked back",
    "side part",
    "undercut",
    "bob",
    "shag",
    "mullet",
    "beehive",
    "pixie",
    "crew cut",
    "fade",
    "comb over",
    "top knot",
]

skin_color = [
    "pale",
    "fair",
    "light",
    "medium",
    "olive",
    "tan",
    "brown",
    "dark",
    "black",
]

skin_texture = [
    "pale",
    "feathery",
    "hairy",
    "spotted",
    "ashen",
    "scaly",
    "scarred",
    "leathery",
    "bumpy",
    "calloused",
    "jaundiced",
    "translucent",
    "bloody",
    "peeling",
    "pierced",
    "mottled",
    "cracked",
    "zitty",
    "oily",
    "cyanotic",
    "transparent",
    "smooth",
    "burnt",
    "sweaty",
    "pasty",
    "veiny",
    "blotchy",
    "warty",
    "waxy",
    "glowing",
    "scabby",
    "bruised",
    "lumpy",
    "patchy",
    "shiny",
    "striped",
    "sickly",
    "sleek",
    "chapped",
    "furry",
    "flaky",
    "tattooed",
    "wrinkled",
    "freckled",
    "pimply",
]

distinguishing_marks = [
    "eyebrow scar",
    "cheek scar",
    "scar",
    "small symbol tattoos",
    "elaborate designed tattoos",
    "light dusting freckles",
    "concentrated freckles",
    "birthmark",
    "mole",
    "piercing",
    "ear piercing",
    "nose piercing",
    "lip piercing",
    "eyebrow piercing",
    "mustache",
    "beard",
    "neck beard",
]
